### ISSUE TITLE
Borders showing when using a custom theme

### ISSUE THREAD

**Issue by arnaudspotfire** [hski-github/spotfire-kanban#3]
When using a different them than light theme, for instance dark theme or a custom theme with a different background color than white the kanban board shows borders.

![Screen Shot 2021-09-09 at 11 37 25](https://user-images.githubusercontent.com/15086293/132662151-ac49e1d7-041c-445b-b9b5-66e19924d22d.png)

**Comment by hski-github** [comment]
th, td in main.css should use margin instead of border-color white. 

Also .card and .card:hover border-color need to use transparent. And .card:hover outline need to use foreground color from theme.

**Comment by hski-github** [comment]
Line colors of the theme can be retrieved from the Mods API

https://tibcosoftware.github.io/spotfire-mods/api-docs/interfaces/stylinginfo.html
https://tibcosoftware.github.io/spotfire-mods/api-docs/interfaces/linestylinginfo.html

![image](https://user-images.githubusercontent.com/1921015/133295609-3e47becb-2d41-4734-a1e9-608cf5ca4e42.png)

**Comment by hski-github** [comment]
Using styling info return "transparent" as background color for both light and dark theme. TIBCO is preparing Spotfire 11.4 H2, which is fixing this issue.

**Comment by hski-github** [comment]
Spotfire 11.4 HF deployed (it says Build-Version: 11.5.0.117, Build-Datum: 23.09.2021) to Spotfire Cloud and Kanban layout working fine in both light and dark theme.
