### ISSUE TITLE
Column selector and kanban vertical spacing

### ISSUE THREAD

**Issue by arnaudspotfire** [hski-github/spotfire-kanban#5]
A bit of space should be added between the column selector bottom and the top of the kanban board. This would add consistency with other Spotfire visuals like the cross table for instance.

![Screen Shot 2021-09-09 at 11 44 08](https://user-images.githubusercontent.com/15086293/132663883-c0d84626-141a-4126-920b-3fe4df28a939.png)

**Comment by hski-github** [comment]
#mod-kanban  in main.css would need some margin-top: 10px;
